version: '2.3'
services: 
  conda:
    build: .
    image: katsu-atmacup-5
    container_name: katsu-atmacup-5-conda
    tty: true
    command: /bin/bash
    volumes: 
      - ./:/analysis
      - ${DATA_DIR}:/analysis/input
    env_file: .env